// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  // Used only by Prisma CLI commands (migrate/introspect) — needs a direct,
  // non-pooled connection because PgBouncer-style poolers (Neon, Vercel
  // Postgres) can't hold the session-level advisory lock migrations take.
  // The app's runtime client never reads this; it's given DATABASE_URL
  // (which can stay pooled) directly in src/lib/prisma.ts.
  datasource: {
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
